// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnuhlnajvGsDumGeXF-LMg8jgN2VjOzrI',
    appId: '1:1057266834821:web:143eff0b509c6d8b92b8ec',
    messagingSenderId: '1057266834821',
    projectId: 'restaurantmanager-dc0d0',
    authDomain: 'restaurantmanager-dc0d0.firebaseapp.com',
    storageBucket: 'restaurantmanager-dc0d0.firebasestorage.app',
    measurementId: 'G-J599BEK6E1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU85KwS7h65amiRXmHthmxjbJCXzF6zX0',
    appId: '1:1057266834821:ios:0611b325015aa2f992b8ec',
    messagingSenderId: '1057266834821',
    projectId: 'restaurantmanager-dc0d0',
    storageBucket: 'restaurantmanager-dc0d0.firebasestorage.app',
    iosBundleId: 'com.example.belleEnvie',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU85KwS7h65amiRXmHthmxjbJCXzF6zX0',
    appId: '1:1057266834821:ios:0611b325015aa2f992b8ec',
    messagingSenderId: '1057266834821',
    projectId: 'restaurantmanager-dc0d0',
    storageBucket: 'restaurantmanager-dc0d0.firebasestorage.app',
    iosBundleId: 'com.example.belleEnvie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnuhlnajvGsDumGeXF-LMg8jgN2VjOzrI',
    appId: '1:1057266834821:web:2d58e207d688780d92b8ec',
    messagingSenderId: '1057266834821',
    projectId: 'restaurantmanager-dc0d0',
    authDomain: 'restaurantmanager-dc0d0.firebaseapp.com',
    storageBucket: 'restaurantmanager-dc0d0.firebasestorage.app',
    measurementId: 'G-DEDMHQFGEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9xNpGqW36el-vvP1VVHE7ZkTtzHH99A',
    appId: '1:1057266834821:android:d5a51c5505b7e79e92b8ec',
    messagingSenderId: '1057266834821',
    projectId: 'restaurantmanager-dc0d0',
    storageBucket: 'restaurantmanager-dc0d0.firebasestorage.app',
  );
}
